### ISSUE TITLE
mpiP: important part of mpiP report is missing in test output file

### ISSUE THREAD

**Issue by ericvh** [arm-hpc/ohpc#51] opened 2016-11-11 04:57 UTC
## Current Behavior
```
not ok 5 [perftools/mpiP] C   binary generates profile data on two nodes under resource manager (/gnu/openmpi)
# (in test file test_mpiP, line 90)
#   `grep -A3 Callsites *.mpiP | grep Allreduce | grep -q C_test.c' failed
not ok 6 [perftools/mpiP] C++ binary generates profile data on two nodes under resource manager (/gnu/openmpi)
# (in test file test_mpiP, line 113)
#   `grep -A3 Callsites *.mpiP | grep Allreduce | grep -q CXX_test.c' failed
not ok 7 [perftools/mpiP] F90 binary generates profile data on two nodes under resource manager (/gnu/openmpi)
# (in test file test_mpiP, line 136)
#   `grep -A3 Callsites *.mpiP | grep Allreduce | grep -q F90_test.f90' failed
FAIL test_mpiP (exit status: 1)


```

**Comment by pawosm-arm** [comment] 2016-12-06 18:21
Please do attach mpiP/tests/test-suite.log too.

The only thing could I get when I started it on TACC manually was:

1..7
ok 1 [perftools/mpiP] Verify MPIP module is loaded and matches rpm version (gnu/openmpi)
ok 2 [perftools/mpiP] Verify module MPIP_DIR is defined and exists (gnu/openmpi)
ok 3 [perftools/mpiP] Verify module MPIP_LIB is defined and exists (gnu/openmpi)
ok 4 [perftools/mpiP] Verify static library is available in MPIP_LIB (gnu/openmpi)
not ok 5 [perftools/mpiP] C   binary generates profile data on two nodes under resource manager (/gnu/openmpi)
# (from function `assert_success' in file ./common/test_helper_functions.bash, line 58,
#  in test file test_mpiP, line 81)
#   `assert_success' failed
#
# -- command failed --
# status : 160
# output (2 lines):
#   Unknown Host.
#   qsub: cannot connect to server CHANGE_THIS_TO_PBS_PRO_SERVER_HOSTNAME (errno=15008)
# --
...

Note that to make qsub work I had to provide path to it explicitly:

PATH=/opt/pbs/bin:$PATH make -k check

**Comment by pawosm-arm** [comment] 2016-12-07 12:24
ok, I managed to reproduce it on RHEL7.2 on Juno and I didn't even have to install pbspro/qsub, automagically it used slurm instead.

**Comment by pawosm-arm** [comment] 2016-12-07 12:47
It's not like there's no output files, I can clearly see them, though no 'Allreduce' phrase is there.

**Comment by pawosm-arm** [comment] 2016-12-07 13:09
IMHO this is the case of lame pattern matching rather than real issue with tested software.

**Comment by pawosm-arm** [comment] 2017-01-09 13:40
The reason why there's no C_test.c in the mpiP output file is that important part of mpiP report is missing: the callsites table is empty:
`
---------------------------------------------------------------------------
@--- Callsites: 1 ---------------------------------------------------------
---------------------------------------------------------------------------
 ID Lev File/Address        Line Parent_Funct             MPI_Call
---------------------------------------------------------------------------
`
This table should list all MPI calls (in case of this test case it is only Allreduce) from all test case source files (should be C_test.c) - and this is what's missing. Only aggregate table for MPI calls is filled with data:
`
---------------------------------------------------------------------------
@--- Aggregate Time (top twenty, descending, milliseconds) ----------------
---------------------------------------------------------------------------
Call                 Site       Time    App%    MPI%     COV
Allreduce               1       4.15   93.85  100.00    0.39
---------------------------------------------------------------------------
`

Seems like mpiP is not able to collect these detailed information therefore they are not printed in the report which is examined by test suite scripts. This leads to a suspicion that mpiP is not properly supported on AArch64 therefore we can't close this issue.

**Comment by pawosm-arm** [comment] 2017-01-09 19:00
I compared x86_64 vs AArch64 build log and found this in AArch64 log (no such warning in x86_64 log):

`
[  570s] mpiPi.h:320:2: warning: #warning "No stack trace mechanism defined for this platform." [-Wcpp]
[  570s]  #warning "No stack trace mechanism defined for this platform."
[  570s]   ^
`
This could be potential reason for the problem.

**Comment by pawosm-arm** [comment] 2017-01-10 20:08
pull request accepted, fixed.

**Closed by pawosm-arm** 2017-01-10 20:08 UTC
Labels: CentOS-7.2, SLES-12-SP1, test
